### PR TITLE
Add slack badge

### PR DESCRIPTION
**Pull request by sergiors**
Someone know why slack badge has height `150px`?

https://github.com/sergiors/quack/blob/8be4bdb1d5f9b6a1387a4ab79f913bccd7a62fe4/README.md

### CODE REVIEW

**Comment by haskellcamargo** [comment]
Well, I don't know why in the world the badge is with the wrong height.

**Comment by haskellcamargo** [comment]
You can force `height: 20px`.

**Comment by haskellcamargo** [comment]
And we are no longer using Gitter. It would be nice to remove its badge too! :smile:

**Comment by sergiors** [comment]
Done ;)

**Comment by haskellcamargo** [comment]
LGTM!

**Comment by sergiors** [comment]
LGTM 😎

**Pull request merged**
