### PR TITLE
[WIP] Removing Python references from the compiler (#12)

### PR DESCRIPTION
**Pull request by joaolucasl**
This PR addresses issue #12, and the commits do:
- [x] Remove the reference from [Makefile](https://github.com/quack/quack/blob/master/Makefile#L10)
- [x] Remove methods from [`src/ast/expr`](https://github.com/quack/quack/tree/master/src/ast/expr)
- [x] Remove methods from [`src/ast/stmt`](https://github.com/quack/quack/tree/master/src/ast/stmt)
- [x] Remove reference from [Quack REPL](https://github.com/quack/quack/blob/master/src/repl/QuackRepl.php#L83)
- [x] Remove method from [TokenReader]

### CODE REVIEW

**Comment by sergiors** [comment]
I think the Python format should be moved, don't removed

**Comment by haskellcamargo** [comment]
It is being _removed_ because the current code is almost useless. It'll be _completely_ rewritten. The current source was there only to annoy my OCD.

**Comment by haskellcamargo** [comment]
LGTM.

**Comment by sergiors** [comment]
Got it.

**Comment by sergiors** [comment]
LGTM

**Comment by haskellcamargo** [comment]
Fixes #12.

**Pull request merged**
