### PR TITLE
Class-based programming

### PR DESCRIPTION
**Pull request by haskellcamargo**
This pull-request implements the basis and aims to define the behavior of class-based-programming on Quack compiler. We need to discuss before merging it.

Currently, the following approach is implemented in this PR:
- There are no interfaces. Classes implement protocols (that variables may also do)
- There are no `final` nor `abstract` classes. Abstraction is defined by the type system and we must discuss if `final` should be implemented
- Properties are defined with the keyword `member`
- Private items are named by a preceding `_`
### Current definition example

``` ocaml
class Tuple
  member a; b
  init[ %self a; %self b ] end (* %self makes a direct member attribution *)
  fn fst! ^ self.a end
  fn snd! ^ self.b end
end

let pair :- #Tuple { 1, 2 }
do print[ pair.fst! ]
```

I'm also proposing operator overloading:

``` sml
class Tuple
  [... stuff ...]
  operator (+)[other]
    #Tuple { self.a + other.a; self.b + other.b }
  end
end

let pair1 :- #Tuple { 1; 2 }
let pair2 :- #Tuple { 3; 4 }
do var_dump[ pair1 + pair2 ] (* (4; 6) *)
```
### Votes
- [ ] Implement final classes
- [ ] Use explicit visibility modifiers
- [ ] Implement support for trait injection
- [ ] Operator overloading for class
- [ ] Multiple inheritance
- [ ] Partial classes

Please, if you want to vote (or discuss), comment what you believe is good to be implemented in the section `votes` and what not (and why).

Note that we want to keep Quack grammar as simple and extensible as possible. Avoid reserving keywords. Also remember that Quack doesn't target _only_ PHP, but a set of languages and VMs.
### My votes
- [ ] Implement final classes
- [ ] Use explicit visibility modifiers
- [x] Implement support for trait injection
- [x] Operator overloading for class
- [ ] Multiple inheritance
- [x] Partial classes

### CODE REVIEW

**Comment by haskellcamargo** [comment]
@marcioAlmada, if you have some suggestion about this and features based on classes that the language should support...

**Comment by luizperes** [comment]
I don't think that **final** should be that important for Quack, and if I'm not wrong, we have extensions, correct? Wouldn't **final** classes have problems with extensions? For example: 

``` Swift
extension to_string for * : T {
  ^ strval[ <T> self ]
}
```

One question is... With non-explicit access modifiers, will Quack have `protected`?

My vote:
- [ ] Implement final classes 
- [ ] Use explicit visibility modifiers // I like the idea of prefixing `private` with `_`
- [x] Implement support for trait injection
- [x] Operator overloading for class
- [x] Multiple inheritance
- [x] Partial classes // as long as we do that using extensions

**Comment by haskellcamargo** [comment]
I'm ok with extensions and partial classes, since they are not conditionally added, because it would break the type system and make it unsound (it already is, BTW). Checking the point of extensions, I see it is ok to implement partial classes, to divide the business logic and behaviors in the same class. We'll still discuss a better syntax for extensions. The current is still unimplemented.

We wouldn't have `protected`. Vertical inheritance can guide to complex code and a big spaghetti. We'll allow it, but enforce horizontal. I'm also thinking about renaming `class` to `blueprint` or `object`. What do you think about?

**Comment by luizperes** [comment]
@haskellcamargo That makes sense! Well, I like `blueprint` a lot better, using my Instructor's hat. It's more intuitive to use it instead of `object` or even `class`. Also, blueprints are the best way to explain the differences between classes' prototypes and instances anyways. I like it. (Y)

**Comment by haskellcamargo** [comment]
Well, I believe it is better we merge the current changes (that fixes some other issues also) and continue the discussion in the issues. 
In the moment, `self` LGTM.

**Comment by sergiors** [comment]
lgtm

**Pull request merged**
