### PR TITLE
Fix function implementation

### PR DESCRIPTION
**Pull request by haskellcamargo**
This pull-request fixes some weird behaviors in functions and removes the necessity of a more advanced _lookahead_ in the parser.

### CODE REVIEW

**Comment by joaolucasl** [comment]
Just for clarification, why was the 'deriving' keyword removed from code? This keyword won't be used anymore?

**Comment by haskellcamargo** [comment]
Yes, the word `deriving` had no sense. It was replaced by `in`:

``` ocaml
let x :- 10
do (fn { y | x + y } in x)[ 20 ] (* 30 *)
```

**Comment by joaolucasl** [comment]
LGTM then

**Comment by haskellcamargo** [comment]
`self` LGTM.

**Pull request merged**
