### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by cuchi**
This file generates a docker image bundled with Alpine Linux and PHP 7.1, which sums up to ~57MB.

By default it start the REPL mode, but it can be used to build other images using the `quack` executable.

### CODE REVIEW

**Comment by haskellcamargo** [comment]
Missing `LABEL maintainer` :smile:

**Comment by luizperes** [comment]
@haskellcamargo I knew you would say that! hahah

**Comment by haskellcamargo** [comment]
# Thank you :heart: 
You made a duck happy!

**Review by haskellcamargo — COMMENTED** [review]
Approved!

**Pull request merged**
