### PR TITLE
ExtensionStmt without regex support

### PR DESCRIPTION
**Pull request by luizperes**
This PR is related to the PRs https://github.com/quack/quack/pull/57 and https://github.com/quack/quack/pull/54

List of valid examples

``` Swift
extension for House
   member nRooms ; nBathrooms 
   fn rooms[] 
     ^ self.nRooms
  end 
end
```

``` Swift
extension for String # UTF8Encoding ; Base64
   ...
end
```

``` Swift
extension for String ; Int # Base64
   ...
end
```

The **example below** is not supported anymore

``` Swift
// gets any file that finishes with "Controller" and the String blueprint, implements the DataProtocol
extension for /\w*Controller/g ;  String # DataProtocol
   ...
end
```

### CODE REVIEW

**Comment by haskellcamargo** [comment]
This branch has conflicts. I'm unable to merge by the visual interface. I believe that the `TODO.md` file is causing this (I've also removed the `.php`). Can you try to remove it from the PR? :smile:

**Comment by haskellcamargo** [comment]
LGTM!

**Comment by luizperes** [comment]
Hey @haskellcamargo. I've done it. Could you check it please?

Thanks!

**Comment by luizperes** [comment]
`self` LGTM

**Pull request merged**
