### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iagocaldeira**
vim syntax

### CODE REVIEW

**Comment by sergiors** [comment]
lgtm

**Comment by haskellcamargo** [comment]
Replace `[quack/editor/vi/quack.vim]` by `[quack/editor/vim/quack.vim]` and we can merge.

**Review by iagocaldeira — COMMENTED** [review]
updated

**Comment by haskellcamargo** [comment]
LGTM.

**Comment by luizperes** [comment]
i'm late, but LGTM! :)

**Pull request merged**
